[package]
authors = ["Cloudflare Workers Team <workers@cloudflare.com>"]
edition = "2018"
name = "worker-sandbox"
version = "0.1.0"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
default = ["console_error_panic_hook"]

[dependencies]
blake2 = "0.10.4"
chrono = { version = "0.4.19", default-features = false, features = [
    "wasmbind",
    "clock",
] }
cfg-if = "1.0.0"
console_error_panic_hook = { version = "0.1.7", optional = true }
getrandom = { version = "0.2.6", features = ["js"] }
hex = "0.4.3"
http = "0.2.6"
regex = "1.5.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
wee_alloc = { version = "0.4.5", optional = true }
worker = { path = "../worker", version = "0.0.9" }
futures = "0.3.21"

[dev-dependencies]
futures = "0.3.21"
reqwest = { version = "0.11.10", features = [
    "blocking",
    "json",
    "multipart",
    "stream",
] }
tokio = { version = "1.18.4", features = ["macros", "rt", "test-util"] }
tungstenite = "0.17.2"
wasm-bindgen-test = "0.3.30"
